#! /bin/bash

# NOTE
# I am currently unable to invoke gmsh from julia so until then meshing the geo file etc
# must be done via bash

if [ "$#" -eq 2 ]; then
	# Dump STDOUT to file
	julia $1 > $2.geo;
	# Meshing
	gmsh -2 $2.geo -o $2.msh
	# Conversion
        dolfin-convert $2.msh $2.xml;
	# Visualization
	python -c "from dolfin import Mesh, MeshFunction, plot, interactive;
mesh=Mesh('$2.xml');
cell_f=MeshFunction('size_t', mesh, '$2_physical_region.xml');
facet_f=MeshFunction('size_t', mesh, '$2_facet_region.xml');
plot(cell_f);
plot(facet_f);
interactive()
"

fi
